export const homeData = [
  {
    id: 1,
    name: "Sand Dust",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan,<br> are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: ["Action", "Adventures", "Horror"],
    cover: "./images/home1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "skull island",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, <br> along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: ["Adventures", "Animation", "Family"],
    cover: "./images/home2.jpg",
    video: "../video/video2.mp4",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Pirates Sea",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, <br> typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: ["Adventures", "Action "],
    cover: "./images/home3.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2010",
  },
  {
    id: 4,
    name: "Sand Dust",
    rating: 4.9,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan,<br> are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: ["Action", "Adventures", "Horror"],
    cover: "./images/home4.jpg",
    video: "../video/video4.mp4",
    date: "12-Aug-2015",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "./images/upcome/u1.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "./images/upcome/u2.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "./images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "./images/upcome/u4.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "./images/upcome/u5.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "King of Jungle",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u7.jpg",
    name: "The illusion",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u1.jpg",
    name: "Latest Movie",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u5.jpg",
    name: "Latest two",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u4.jpg",
    name: "Latest Three",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "The Dinosaur",
    rating: 4.7,
    time: "2hr : 22mins",
    desc: "Sand and dust storms (SDS), also known as sirocco, haboob, yellow dust, white storms, and the harmattan, are a natural phenomenon linked with land and water management and climate change.",
    starring: "Karen Gilchrist, James Earl Jones",
    genres: "Action",
    tags: ["Action", "Adventures", "Horror"],
    cover: "../images/img/slide1.png",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "The Great Emperor",
    rating: 4.6,
    time: "2hr : 22mins",
    desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Adventures",
    tags: ["Adventures", "Animation", "Family"],
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Jumbo Queen",
    rating: 4.8,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: ["Adventures", "Action "],
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "One Man Army",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Jumbo Queen",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "My office Boss",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Shadowe",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Another Danger",
    time: "2hr : 38mins",
  },
]

export const popularData = [
  {
    id: 1,
    name: "The Matrix Resurrections",
    rating: 4.5,
    time: "2hr : 28mins",
    desc: "Return to a world of two realities: one, everyday life; the other, what lies behind it. To find out if his reality is a construct, Mr. Anderson will have to choose to follow the white rabbit once more.",
    starring: "Keanu Reeves, Carrie-Anne Moss",
    genres: "Action, Sci-Fi",
    tags: ["Action", "Sci-Fi", "Adventure"],
    cover: "./images/popular/matrix.jpg",
    date: "2021",
  },
  {
    id: 2,
    name: "Dune",
    rating: 4.8,
    time: "2hr : 35mins",
    desc: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
    starring: "Timothée Chalamet, Rebecca Ferguson",
    genres: "Sci-Fi",
    tags: ["Sci-Fi", "Adventure", "Drama"],
    cover: "./images/popular/dune.jpg",
    date: "2021",
  },
  {
    id: 3,
    name: "Spider-Man: No Way Home",
    rating: 4.7,
    time: "2hr : 28mins",
    desc: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
    starring: "Tom Holland, Zendaya",
    genres: "Action, Adventure",
    tags: ["Action", "Adventure", "Fantasy"],
    cover: "./images/popular/spiderman.jpg",
    date: "2021",
  },
  {
    id: 4,
    name: "The Batman",
    rating: 4.6,
    time: "2hr : 56mins",
    desc: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    starring: "Robert Pattinson, Zoë Kravitz",
    genres: "Action, Crime, Drama",
    tags: ["Action", "Crime", "Mystery"],
    cover: "./images/popular/batman.jpg",
    date: "2022",
  },
  {
    id: 5,
    name: "Top Gun: Maverick",
    rating: 4.9,
    time: "2hr : 11mins",
    desc: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission.",
    starring: "Tom Cruise, Miles Teller",
    genres: "Action, Drama",
    tags: ["Action", "Drama", "Adventure"],
    cover: "./images/popular/topgun.jpg",
    date: "2022",
  },
  {
    id: 6,
    name: "Black Panther: Wakanda Forever",
    rating: 4.7,
    time: "2hr : 41mins",
    desc: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    starring: "Letitia Wright, Angela Bassett",
    genres: "Action, Adventure",
    tags: ["Action", "Adventure", "Drama"],
    cover: "./images/popular/blackpanther.jpg",
    date: "2022",
  },
  {
    id: 7,
    name: "Avatar: The Way of Water",
    rating: 4.8,
    time: "3hr : 12mins",
    desc: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    starring: "Sam Worthington, Zoe Saldana",
    genres: "Action, Adventure, Fantasy",
    tags: ["Action", "Adventure", "Fantasy"],
    cover: "./images/popular/avatar2.jpg",
    date: "2022",
  },
  {
    id: 8,
    name: "Everything Everywhere All at Once",
    rating: 4.9,
    time: "2hr : 19mins",
    desc: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    starring: "Michelle Yeoh, Ke Huy Quan",
    genres: "Action, Adventure, Comedy",
    tags: ["Action", "Comedy", "Sci-Fi"],
    cover: "./images/popular/everything.jpg",
    date: "2022",
  },
  {
    id: 9,
    name: "Oppenheimer",
    rating: 4.8,
    time: "3hr : 00mins",
    desc: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    starring: "Cillian Murphy, Emily Blunt",
    genres: "Biography, Drama, History",
    tags: ["Drama", "History", "Biography"],
    cover: "./images/popular/oppenheimer.jpg",
    date: "2023",
  },
  {
    id: 10,
    name: "Barbie",
    rating: 4.7,
    time: "1hr : 54mins",
    desc: "Barbie suffers a crisis that leads her to question her world and her existence. Join her on a journey of self-discovery in the real world.",
    starring: "Margot Robbie, Ryan Gosling",
    genres: "Adventure, Comedy, Fantasy",
    tags: ["Comedy", "Adventure", "Fantasy"],
    cover: "./images/popular/barbie.jpg",
    date: "2023",
  }
];

export const genreData = {
  Action: {
    count: 245,
    cover: "../images/genres/action.jpg",
    description: "Thrilling action-packed movies"
  },
  Drama: {
    count: 189,
    cover: "../images/genres/drama.jpg",
    description: "Emotional and compelling stories"
  },
  Comedy: {
    count: 167,
    cover: "../images/genres/comedy.jpg",
    description: "Laugh-out-loud entertainment"
  },
  Horror: {
    count: 123,
    cover: "../images/genres/horror.jpg",
    description: "Spine-chilling horror films"
  },
  "Sci-Fi": {
    count: 145,
    cover: "../images/genres/scifi.jpg",
    description: "Mind-bending science fiction"
  },
  Romance: {
    count: 156,
    cover: "../images/genres/romance.jpg",
    description: "Heart-warming love stories"
  }
};
